# Generated by Django 5.2 on 2025-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="accessibility_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="devices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="employment",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_disability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="income",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_single_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="opportunity_preferences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_work_format",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
