# Generated by Django 5.2 on 2025-05-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='income',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='opportunity_preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_work_format',
        ),
    ]
